Feature: Solve the challenge Can-You-Read-Me
  From www.wechall.net
  With my username SYLAR

  Scenario: Succesful Solution
    Given an image
    When I read html source
      And I see the image source is generated by a php
      And I install tesseract with apt
      And I use wget to download the captcha using my cookie
      And I use tesseract to put the captcha in a txt file
      And I research how to sent a post data with curl
    Then  I make a sh file to do all the proccess
        And I find the solution
    Then I solve the challenge
